- data/update-lich5.json
Lich 5 users are running the gambit from 5.0.4 up.  
5.0.18 data corrected to include lib files irrespective of existing version to correct.
> Too many users on less than 5.0.16!

- scripts/infomon.lic
This is a regex defect fix.  Revving to 1.18.10 (was 1.18.9)
> Update spell regex Cloak of Shadows / Raise Dead

- lich.rbw
Release candidate 5.0.19:  Includes:
1) Monks using Feat mental acuity will cast using stamina, rather than mana.  Updated waggle to match.
2) Capture PSM3 XML to present via Effects module
-o- `.to_h` faithfully renders the appropriate Effects category
-o- `.active?` accepts either Integer or Effect name (capitalization counts)
3) Provides PSM3 durations to XMLData.active_spells for legacy script use
> Release Candidate for 5.0.19

- scripts/lich5-update.lic
The --snapshot feature fails in certain test cases where the existing lich version is the same as the current json lich version.  These changes address validations and permit the --snapshot feature to function.  Adding directly to master branch to limit poor update experiences.
> Update --snapshot lich5-update

- scripts/lich5-update.lic
Per Rinualdo - reduce confusion by returning a message when the script is run but no action is needed, or when the script is run without parameters / arguments.
> Update text / reduce confusion - lich5-update

- lib/spell.rb
Detected at test - correction before launch
Added end statement for class that was missed in splitting code.  Merging in 30 minutes.
> bug / spell.rb syntax error (missing end)

- lib/constants.rb
Did not include the deprecated global dir variables initially.  This corrects the oversight
> Adding deprecated global dirs to constants.rb

- lich.rbw
5.2.1 disabled sal files based on the deprecation tests for Windows platforms.  The popular script ;login uses sal files to facilitate logging in other characters while in game.   This PR re-enables the deprecated code required for ;login to work unmodified.
> Emergency restore sal to lich

- data/update-lich5.json
Setting up snapshot to be version agnostic - json entry
> Chore: Update lich5 updater json to support snapshots

- lich.rbw
if a rusty doorknob is in a room, and a mundane "go door" wayto fails because of it code changes the exit to "go second door" (or third, fourth. it tries to iterate based on the exit). However, it changes the entire room in memory not just the command issued to the game while issuing that movement so it persists for the entire session. If the doorknob is then removed, the exit is now broken until the player logs out or reloads the mapdb.
by casting the "dir" var to a string first, we avoid this issue by manipulating a temporary string var and not a reference to the map DB in memory itself.
example:
```
>drop doork
You drop a rusty doorknob.
--- Lich: go2 active.
[go2: ETA: 0:00:00 (1 rooms to move through)]
>;go2 13198
[go2]>go door
You take a few steps toward a rusty doorknob.
[go2]>go …
```
> [lich.rbw] avoid stomping exits because of doorknobs

- lib/init.rb
While not broken, the Linux | WINE method of FE launch still relies on SIMU Launcher or SIMU SGE -> SIMU Launcher.  This incorporates the method to determine where the FE is stored, for use by Lich without needing either Launcher or SGE
> Add Linux WINE to direct FE launch methods

- lib/xmlparser.rb
- scripts/infomon.lic
This is a significant change to Infomon that paves the direction for a future rewrite based on the Effects module. In short, it stops looking for up / down messages from spells and simply takes in the current xmlparser active_spells output. There are some names that are then transformed to conform with current naming conventions in spell-list.xml and various scripts to limit breaking changes.
Needs thorough testing.
> Update infomon to track spell durations accurately

- lich.rbw
waitrt? and waitcastrt? do not return any values, they simply sleep.  The function will now sleep and then return true or return false immediately for scripts expecting a returned value.
> Update waitrt? / waitcastrt? to return true/false

- lich.rbw
Recent XML frequency changes and increased time in allowing characters to remain inactive have led to an increase in firing of the legacy lich method of timing out after 5 minutes of no server messages.
Removes the thread that watched for 5 minutes and then logged out.
> Remove 5 minute timeout

- lib/init.rb
I have wine installed, but do not use it with lich. 
This is just a hack, to prevent lich crashing on load in this scenario. I can only assume this doesn't work anyway, since `$sf_fe_loc` is undefined, but it won't be an issue for most people. Linux being an edge case, and then having wine, but not using it for lich... Anyway, this let's me launch lich without crashing on linux.
> Stops lich crashing on load when wine is installed, but not used

- scripts/infomon.lic
Infomon updated to deal with 712 / 520 when `set showspellname off`
> Correct spell numbers 712 / 520

- lib/xmlparser.rb
Adding the tags 'Cooldown' and 'Debuff' so that spell-list.xml spell detection of 'Cooldown' and recovery is back in operation.
> Re-date xmlparser to add 'Cooldown' and 'Debuff'

- lib/gui-login.rb
- lib/gui-manual-login.rb
Reported by Athias - incorrectly entered account / password information in Lich 5 GUI errors, but does not present a modal dialog with explanation as intended.
Repairs this issue.
> Fixing variable to instance variable for login dialog window

- lich.rbw
bugfix for sorting of script selection when running.
Issue: if you have two scripts named similar like go2.lic and go2-backup.lic it would run go2-backup. 
Example:
```
;go2 town
[go2-backup: ETA: 0:00:00 (1 rooms to move through)]
```
Issue due to switching from sort_by to sort
> Update lich.rbw script lookup sorting

- lich.rbw
Preventing class Script from pushing empty arguments to scripts being loaded
This change modifies class Script to prevent empty or nil arguments being passed to scripts as they're being loaded.  Scripts that do not accept arguments were unaffected by recent Lich 5.4.x changes, but those scripts that did accept arguments, but did not intend to catch NIL or EMPTY arguments showed erratic behavior.
edited for spelling
> Script CLASS empty array initializing bugfix

- lib/spell.rb
Add extra Spell options:
Does not currently know what spells can be channel or evoke. Will attempt and if can't evoke/channel, switch to cast instead.
> Add Spell.incant, Spell.channel, Spell.evoke

- lich.rbw
Fix to allow Effects module to use FLOAT instead of INTEGER for timeleft/active defs.
> Fix for FLOAT math on Effects module

- scripts/autostart.lic
This change adds dependency start into autostart ahead of processing any other scripts, and does not start drinfomon - drinfomon is initiated by dependency.
Solves
1) dependency only starts on initial run
2) drinfomon tries to start before dependency is active
3) drinfomon would fail because dependency already starts it
> Adjusting autostart for DR to run dependency appropriately

- scripts/autostart.lic
DR has the feature where drinfomon dynamically loads when required, so loading it in autostart is unnecessary.
> Removing drinfomon from starting in autostart

- scripts/autostart.lic
Simple as anything. Just skips dependency if it's additionally listed as an autostart script, and prints a note on how to remove it from the autostart liss.
```
--- dependency found in autostart list. Attempting to remove it now. If unsuccessful, it can be safely removed with ';autostart remove --global dependency'                                                                                   
--- dependency was removed from the global autostart list         
```
> [scripts] [autostart] Skip dependency in autostarts, and instructions on how to remove it.

- lich.rbw
Allows usage of a comma, or the semi-colon as the lich char. In the past, Genie couldn't handle semi-colons, but that's no longer the case.
I don't believe adding the comma as a second command character breaks anything...
> [lich.rbw] Clean lich char comma or semi-colon

- lib/stash.rb
Presently `Stash.add_to_bag` attempts over 0.4 seconds to detect success in putting an item away without needing to check regex.
Most systems / network connections support a 0.2 to 0.4 second success for this method.  Some players report that after the item is stashed, containers are iterated and an attempt is made to place the item in each container or to prepare a spell.  This is the result of exceeding the 0.4 second threshold in detecting success even though the item is stowed as requested.
This change increases the time to detect success to 2 seconds, matching the `Stash.try_or_fail` method.  Since the `Stash.add_to_bag` method returns immediately on detecting success, this will allow the slower systems / network connections to detect success and process properly without adding …
> [lib][stash.rb] Fix duration of Stash.add_to_bag

- data/update-lich5.json
The old 5.5.0 spec didn't have update.rb, global_defs.rb and updated map.rb - these are added while we're preparing the 5.6 transition.
> Emergency blue button to include needed files

- lib/gui-login.rb
- lib/gui-saved-login.rb
- lib/lich.rb
- lich.rbw
After resetting staging to master, bringing these two ROWO variable initialization fixes back - 
one on displaying lichid / uid that was calling lich.db3 at room transition / look (and sometimes multiple times), and for each character.   Imagine go2 at full speed, with an army following, all hitting the same local lich.db3 at room transition. 
two is the same change for like lich variables stored in the db3 file - not nearly as beneficial from a performance perspective, but consistency was the goal for that change.
> Adding boolean calls and gui fixes back

- lib/update.rb
Needed to place --refresh before the --revert CASE statement due to regex matching `-r` for revert before it could ever get to `--refresh`
> [update.rb] bug in order of options parsing

- lib/xmlparser.rb
Modify XMLData.active_spells so that spells with the text 'Recovery' in the spell.name do not get the text 'Cooldown' added to the spell.name.  
Affects several wizard spells (Celerity Recovery, Rapid Fire Recovery, etc).  
Keeps spell.name in line with expectations for spell_list.xml (for now).
> Fix: xmlparser.rb - xmldata-active-spell for cooldowns

- data/update-lich5.json
- lib/version.rb
Two files updated to support LNet deprecation in master build.  Removed from autostart (can be manually added) and removed from repository's 'set updatable' (can be manually added).  Thanks, Tysong!
> Pulling forward LNet Deprecation into 5.6.1 release

- lib/global_defs.rb
- scripts/autostart.lic
The logic for update.rb did not operate without a parameter.  This change detects no parameter provided and presents the --help information back to the user. Thanks, Tysong!
> Pulling forward small update to update.rb

- lib/cman.rb
- lib/feat.rb
- lib/shield.rb
- lib/weapon.rb
the `available?` check for cman and cman like abilities was using the old Strained Muscles debuff name. This was renamed to overexerted some time back.
> Strained Muscles was renamed to Overexerted

- lib/global_defs.rb
In splitting global_defs.rb from lich.rbw, somehow managed to lose the `lich_char_regex` for `do_client` def.  This PR fixes that.
> Add lich_char_regex back to do_client

- lib/global_defs.rb
In some rooms outside of Ratha (such as 5120), the `move` function in lib/global_defs.rb, called by go2.lic, was not catching slips:
```
[go2]>southwest
You slip in the mud and fall flat on your back!
>
[go2: move: no recognized response in 10 seconds.  giving up.]
[go2: restarting script...]
[go2: ETA: 0:00:10 (55 rooms to move through)]
[go2]>stand
You stand back up.
>
```
This PR adds a regex which catches this slip text, and go2 now seems to work as expected:
```
[go2]>southeast
You tramp southeast.
[Reshalia Trade Road, Farmland]
The road takes a sharp turn here at the corner of a field.  The ground underfoot is soft and squishy, with frequent stretches that are downright slippery.  The smell of healthy, wet slime gives you a clue as to why this piece of road is so hazardous -- it's …
```
> [global_defs.rb] Adds another slip text match in the move function

- .gitignore
Adds two folders to .gitignore.
`data/DR` to mirror the fact we already ignore `data/GSIV`
and
`scripts/` since no master copies of scripts live in this repo anyway, and this conflicts with folks who clone other repos and populate this directory.
> [.gitignore] Adding data/DR/ and scripts/ to ignore list

- lib/global_defs.rb
Like to add a few lines to global_defs, dealing with move method and items at your feet:
```ruby
elsif line =~ /^You notice.* at your feet, and do not wish to leave it behind/
fput "lift"
fput "stow"
sleep 1
put_dir.call
```
inside move method.
```
>;go2 pond
--- Lich: go2 active.
[go2: ETA: 0:00:02 (12 rooms to move through)]
[go2]>south
You notice some ojhenik potion at your feet, and do not wish to leave it behind.
>
[go2]>lift
You pick up the potion lying at your feet.
>
[go2]>stow
You put your potion in your entangling brambles.
>
[go2]>south
You notice some sufil sap at your feet, and do not wish to leave it behind.
>
[go2]>lift
You pick up the sap lying at your feet.
>
[go2]>stow
You put your sap in your entangling brambles.
>
[go2]>south
```
With the new lift verb, this doesn't …
> [global_defs.rb] at feet handling to move method

- lib/update.rb
Fix an issue in the download_update def when spaces in dire path due to not using `File.join`
> [update.rb] fix spaces in DIR path bug

- lib/global_defs.rb
Used assignment instead of comparison when looking at wound levels.
> [global_defs.rb] empty_hand bugfix

- lich.rbw
Add `--drt` and `--gst` to lich.rbw ARGV patterns to allow login to test instance without needing to have duplicate login entries saved.
> [lich.rbw] add test instance login bypass

- lib/gui-manual-login.rb
- Caused by Invalid use of pattern-matching operator from an array
Closes Connect hangs trying to get character list on Ruby 3.2.1 on Windows. #290
> Resolves hang on connect issue on Ruby 3.2.1 on windows

- lib/gui-saved-login.rb
- Add all DR game codes for tabbed layout gui
- Add specific code for GS3 instead of relying on falling through to else
- Add unknown in case not matching any current known gamecodes.
> [lib/gui-saved-login.rb] Fix mismatch on tabbed GUI and instance names

- lib/gui-manual-login.rb
The text of the @custom_launch_dir combo box is incorrectly being used to overwrite the whole object itself when being saved, instead of fetching that text and saving it to a new local variable which is actually used during the save
Until PR #285 is merged, this won't have much effect, as setting custom launch commands aren't currently accessible from the gui.
> [lib/gui-manual-login.rb] Fixes issue of using wrong variable for custom_launch_dir during save

- lib/init.rb
- lich.rbw
Acts the same as `unset DISPLAY` on linux, but allows a windows instance to go gtk3-free
> [lich.rbw][init.rb]Add handling for no-gui on windows

- lich.rbw
converting system call to spawn (may not work on non Ruby 3.2)
> BUGFIX: Update for Ruby 3.2 to start SIMU FE

- lib/update.rb
Bugfix for Ruby v3 `open` syntax for a URL to use URI.open
> [update.rb] URI bugfix for individual file update

- lib/init.rb
Current Lich will sometimes fail to run for a few attempts and then mysteriously start with no other changes.  The issue is current Lich detects more than 20 files in TEMP_DIR and tries to delete `debug<numbers.log` files over 20.  But many activities (like `;repository`) also save files to TEMP_DIR, leading to a `TRUE` result for more than 20 files, but potentially a `FALSE` result for 20 debug files. 
This change detects only debug files, and actions only debug files to prevent the intermittent failure.
> bugfix:init.rb - detecting 20 files vs detecting 20 lich debug files;

- lich.rbw
GS uses the same login information as prime (assuming the same for DR).  Instead of duplicating login information under game GST, uses the login info from GS3 and applies the appropriate game code.
> [lich.rbw] update entry for test servers

- lib/bounty/parser.rb
- spec/bounty_parser_spec.rb
Moved some of my leveling dudes to RR and noticed that the completed task regex wasn't handling things correctly there. This adds an example bounty to the tests and updates the parser to recognize RR info.
> Bounty API: Adds River's Rest example for guard regex

- .rubocop.yml
Add Layout/FirstHashElementIndentation EnforcedStyle consistent
Will cause hash elements to be indented properly.
Instead of:
```ruby
@locker_items.push({
:id          => id,
:location_id => location_id.to_i,
:level       => level.to_i,
})
```
We'd get
```ruby
@locker_items.push({
:id          => id,
:location_id => location_id.to_i,
:level       => level.to_i,
})```
> [rubocop.yml] add Layout/FirstHashElementIndentation

- lich.rbw
Enables greater flexibility in detached client mode, especially where this is deployed via docker or other containers.  No need to mess with iptables / firewalld / etc within the container.
> [lich.rbw] Add support to specify IP to listen on in detachable client mode

- lib/attributes/society.rb
typo fix for `self.stastus.dup`
> [society.rb] typo fix

- lib/infomon/infomon.rb
contributers is a misspelling of contributors.
> [infomon.rb] update - typo fix

- lib/infomon/infomon.rb
Currently keys should be automatically replacing spacing with `_` characters. But in regards to lore skills, this is currently having an issue due to the `.gsub('_-_', '')` removing the underline as shown via:
```ruby
;e echo Infomon._key('sorcerous lore - necromancy')
[exec1: sorcerous_lorenecromancy] 
```
Replacing the previous to be `.gsub('_-_', '_')` instead now corrects this and has the naming to be:
```ruby
;e echo Infomon._key('sorcerous lore - necromancy')
[exec1: sorcerous_lore_necromancy] 
```
Which matches skills.rb module for returning proper values.
> [infomon.rb] dash space fix for naming keys

- .github/workflows/rspec_tests.yml
No reason to continue a previously still running rspec if another newer rspec action is started. Cancel previous in progress runs.
> [rspec_tests.yml] cancel previous already running rspecs

- lib/infomon/parser.rb
This match was resulting in a string, not an integer.
https://discord.com/channels/690691823542206496/691485066659889212/1121762396583763988
> [core][parser] Add .to_i for integer match

- lib/util.rb
Bug fix to not squelch the end_pattern if not set to quiet.
> [util.rb] fix to not squelch end_pattern

- lib/infomon/cli.rb
- lib/infomon/infomon.rb
- lib/infomon/parser.rb
- lib/infomon/status.rb
- lib/psms.rb
- lib/xmlparser.rb
- spec/infomon_spec.rb
This update returns the `||=` method and adds `Infomon.delete!(key)` method to remove a row from infomon.db.
This update includes webbed, stunned and dead to module `Status`.
This update changes `Infomon.show` to display non-zero values, unless `Infomon.show(true)`.
This update includes parsing and db logic for `Society` joins, promotions, and resignations.
This update includes improved testing for new features and for existing features that did not fully test.
> Society, Infomon.show, .delete! and better testing for infomon

- lib/infomon/status.rb
Had `self.webbed?` using `XMLData.indicator['IconDEAD']` instead of `XMLData.indicator['IconWEBBED']`
> [status.rb] typo for webbed using wrong indicator

- lib/infomon/cli.rb
- lib/stash.rb
- lib/util.rb
Refactor method to use named parameters instead of mandatory order of passed variables. Doing now before live so as easier to maintain going forward.
> chore: refactor Lich::Util.issue_command

- lib/spell.rb
fix for #273
reproduce as col sorcerer: 
reduce spirit to 1 and have spirit draining sign active (e.g. sign of swords), try Spell[401].cast and get 'not enough spirit' error. 
fix: skip spirit check if the spell doesn't require spirit.
> [spell.rb] fix for #273

- lib/xmlparser.rb
- lich.rbw
Allows xmlparser to parse nav tags when nested in the same line as other attributes.
> [lich.rbw][xmlparser.rb] Remove NAV tag rewrites, fix in xmlparser instead

- lich.rbw
DR occasionally has poor encoding in text, which causes parsing errors. One example of this is in the discern text for the spell Membrach's Greed which gets sent as Membrach\x92s Greed. This fixes the bad encoding until Simu fixes it.
Results in:
```
2023-07-14 10:11:02: Detected poorly encoded apostrophe: "<roundTime value='1689286271'/>Named for the Dwarven warlord whose lust for wealth and power propelled his kingdom into disastrous war, certain moralists decry the teaching of Memb
rach\x92s Greed.  Their objections are largely dismissed though, for rather than perverting its target's mentality as commonly believed, the spell pattern selectively hones the natural thought processes related to avidity and discernment,
allowing those under its elegant effect to more easily locate and …
```
> [lich.rbw] Add sub for bad apostrophe encoding string

- lib/update.rb
Fix to match for CLIENT string with or without `<c>` in it for beta testing.
> [update.rb] bugfix for <c> in CLIENT.gets STAGING

- lib/update.rb
Resolves trying to backup a file that does not exist, like the new effect-list.xml
```
--- Lich: error: client_thread: No such file or directory @ rb_sysopen - D:/Lich5/data/effect-list.xml
D:/Lich5/lib/update.rb:234:in `initialize'
```
> [update.rb] bugfix for backing non-existent data files

- lib/bounty/task.rb
- spec/bounty/task_spec.rb
Need to add `:heirloom_found` match for `guard?` method as you need to return to the guard first before going to the taskmaster.
> [task.rb] fix to :heirloom_found for guard?

- R4LGTK3.iss
Change installer name to match version of Lich it's packaged with so instead of `Ruby4Lich5.exe` it's `Ruby4Lich5.7.0-rc.6.exe`
> [R4LGTK3.iss] change final installer name include version

- lib/game-loader.rb
- lib/infomon/activespell.rb
- spec/infomon_spec.rb
- spec/psms_spec.rb
I wasn't able to run the specs locally after some recent changes, so I dug into what was going on. I made a few changes here to get things working locally and to vastly improve the spec run time.  It is also probably not ideal that we download `spell-effect.xml` multiple times per spec run but things happen reasonably fast for me locally that I didn't tackle that.
[3 minutes](https://github.com/elanthia-online/lich-5/actions/runs/5687307741)
[20s](https://github.com/elanthia-online/lich-5/actions/runs/5687369839)
> [specs] Refactor some things to significantly improve rspec run time

- lib/global_defs.rb
Fixes #453 by adding full regex line to match to resolve trying to `move` while hidden and prone.
> [global_defs.rb] bugfix for move def while prone sneaking

- lib/infomon/cli.rb
Save the last time `Infomon.sync` was ran to the db to have a valid check for first run sync and for other debugging needs by setting `Infomon.set('infomon.last_sync', Time.now.to_i)`
> [cli.rb] save last Infomon.sync to db

- lib/update.rb
Changed prod tar retrieval based on suggestion to match beta file fetch method.  Change supports workflow change to delete data files from Lich repo and build EO scripts repo data files into build.
> [update.rb] change method to pull asset tar file

- lib/infomon/parser.rb
SPELL output regex was matching unneccessary game lines as well as creating `spell.circle_base` instead of just `spell.circle` infomon values. Updating regex to be more specific.
> [parser.rb] bugfix for SPELL output

- lib/game-loader.rb
- lib/infomon/activespell.rb
- lib/xmlparser.rb
- spec/activespell_spec.rb
When testing recent updates to lich, I noticed that my CPU usages was significantly higher (ie. redlining multiple CPUs on a modern machine).
After some investigation, it looks like the ActiveSpell watcher spawns a thread that repeatedly checks a new boolean value in the XMLData class.
I refactored this to try a couple of other approaches:
1) Invoke the ActiveSpell method directly instead of setting a boolean. This has greatly reduced CPU usage to less than 1% almost all the time. I understand the motivation for moving this to its own thread though, so I'm testing this especially with lots of scroll and spell updates to make sure it doesn't block processing in the main lich XML parsing routine. 
2) Continue to use the background thread but to switch to a …
> [infomon] Refactor ActiveSpell watcher to use queue

- lib/update.rb
Pull in staging branch version of library to allow for `;lich5-update --update` to pull in release assets instead of source zip
> [update.rb] fix for non-beta release asset

- lib/messaging.rb
- lich.rbw
Add Lich::Messaging.mono(msg) to send msg as mono spaced text and rubocop code cleanup
> [messaging.rb] 1.2.0 mono spaced output

- lib/infomon/parser.rb
- spec/infomon_spec.rb
Fix for redsteel marks as no longer visible via `WEALTH` but `BEAST STATUS` instead.
```
Spirit Beast Information:
Redsteel Marks:            3441
```
> [parser.rb] Infomon::Parser regex update for redsteel marks

- lib/infomon/cli.rb
- lib/infomon/parser.rb
Fixes profession, race, age, and gender getting changed to something not accurate when 1212 Shroud of Deception is active.
> [parser.rb] Infomon::Parser bugfix for 1212 Shroud of Deception

- lib/stash.rb
adding to regex to prevent false positive results detection
> [stash.rb] fix emptyhands bug

- lib/messaging.rb
Fix Lich::Messaging.mono API to correct for Avalon's \n handling being bugged.
> [messaging.rb] mono API fix for \n AVALON bug

- lib/infomon/parser.rb
Update parser to NOT parse SKILLS BASE output, it should be set to only grab SKILLS CURRENT so that it carries enhancive/ascension values.
> [parser.rb] logic fix Infomon::Parser skills current/base

- lib/global_defs.rb
- lib/script.rb
Allow for naming your exec by launching via following:
```
>;execname log echo '1'   
--- Lich: log1 active.    
[log1: 1]                 
--- Lich: log1 has exited.
```
> feat: ExecName - Named execs

- .github/workflows/installer.yml
- .github/workflows/release.yml
Update to include updated lich5-update.lic to force newest version of the script that if on Lich 5.7.0 will cause the script to use built in `update.rb` API library instead. This also allows for continued use of autostart to check if current version is up to date via the `--announce` option
> chore: include recent lich5-update.lic in release/package

- lib/psms/armor.rb
- lib/psms/ascension.rb
- lib/psms/cman.rb
- lib/psms/feat.rb
- lib/psms/shield.rb
- lib/psms/warcry.rb
- lib/psms/weapon.rb
Allows for checking current skill rank by doing: `CMan.berserk` vs the current `CMan['berserk']` that currently existed.
> chore: add individual PSM skill methods for short/long names

- lib/infomon/activespell.rb
- lib/infomon/parser.rb
- spec/infomon_spec.rb
During rewrite of infomon, missed forcing Spellsong.renewed to be done when a song is sang or renewed. Also cleaned up spec-test to not throw as many internal errors on the spec run.
> bugfix: Spellsong with Infomon

- lib/experience.rb
Adds percent experience calls for field experience, ascension experience, and regular experience via `Experience.percent_fxp`, `Experience.percent_axp`, and `Experience.percent_exp`. Partially resolves issue #449
> [experience.rb] percent experience options

- lich.rbw
```
;e UpstreamHook.sources
+---------------+------------+
| Hook          | Source     |
+---------------+------------+
| lnet          | lnet       |
+---------------+------------+
| alias-service | alias      |
+---------------+------------+
| group_ajar    | group_ajar |
+---------------+------------+
| infomon       | infomon    |
+---------------+------------+
```
Adds tracking what script has implemented an up/down stream hook into `UpstreamHook.sources` and `DownstreamHook.sources` that outputs a terminal table output. Useful for tracking down an errant hook from a random source potentially. Done in such a way as to not change any existing behavior the calls (in list, remove, etc.)
> [hooks] adds .sources for up/downstream hooks

- lib/claim.rb
- lib/game-loader.rb
- lib/xmlparser.rb
the `Group` and `Clustered` callouts are kinda holdovers from O's original script not sure if that should just get taken out. but believe this is working. I'm still not running 5.7 as a daily driver but was fine in some impromptu testing and was a port of code i've been running in slightly older lich for months without issue. but there were some changes in xmlparser so might need extra verification.
This would expose `Claim.mine?` that could be use in bigshot et. all checks as well as letting other scripts block on `Claim.last_room == <target room>` to minimize race condition issues parsing room objects, etc.
> [claim.rb] feat: add new claim module and associated changes to xmlparser

- lib/psms.rb
- apostrophes were not accounted for in `PSMS.name_normal` (Predator's Eye)
- stop clobbering the passed argument in name_normal by operating on a different object. the `gsubs!` were changing the passed name all the way up the stack causing unintended side effects
> [psms.rb] stop clobbering with PSMS.name_normal, account for apostrophes

- lib/attributes/skills.rb
Remove erroneous skill `combatleadership` from skills list as hasn't been implemented in a very long time.
> [skills.rb] removal of combatleadership

- lib/global_defs.rb
Remove standalone `<b>`/`</b>` for profanity as Profanity supports pushBold/popBold without issue.
> [all][global_defs.rb] update monsterbold methods

- lich.rbw
Settings, GameSettings, and CharSettings have load, save_all, clear, auto, and autoload methods that do nothing. Adding deprecated warnings to them.
> [all][lich.rbw] deprecate old Settings/GameSettings/CharSettings

- lib/global_defs.rb
- lich.rbw
Existed a bug when using `strip_xml` multiple times. Which happened when called for infomon parsing and then normal Script downstream pushing. This allows for separate multi-line detection in these situations and not cause double downstream buffer push.
> [gs][global_defs.rb] strip_xml multiline bugfix

- lib/effects.rb
Adds support to use regexp in effect lookup of `.active?` and `.time_left`.
> [gs][effects.rb] add regex support for active? & time_left

- lich.rbw
Remove the exclusion of login/logoff/death messaging.
It's not a complete list, and it would be painful to update (players can get custom messaging unique to themselves) with no apparent reason to be excluded.
> [dr][lich.rbw] Remove the exclusion of login/logoff/death messaging in downstream hook

- lib/common/account.rb
- lib/common/eaccess.rb
- lib/common/front-end.rb
- lib/main/main.rb
Currently we only create a session file in `File.join(Dir.tmpdir, "simutronics", "sessions")` if Lich is started with CLI arg of `--detachable-client=PORT`. This PR corrects a logic mistake in that detection as well as creates the same session file for launching from GUI that FEs can utilize if not able to take passed launch parameters to connect to a host/port. Namely Mudlet.
Also adds new `Account.character` api to allow for session file to be written properly.
> [all][main.rb] fix: create session file in regular connect method

- lib/main/main.rb
Mudlet doesn't support real Simutronics integration, so force it if launcher_cmd contains it
> [all][main.rb] fix: Mudlet support

- lib/dragonrealms/drinfomon.rb
- lib/games.rb
- lib/stash.rb
This permits symbols for namespace constants to be defined.
> [all][games.rb]bug:fix namespace constants

- lib/common/hmr.rb
- lib/global_defs.rb
Prevent OS unicode errors due to un-escaped regexp characters
> [all][global_defs.rb] bugfix: regexp escape hmr command

- lib/common/game-loader.rb
- lib/global_defs.rb
removes `require` from global_defs when attempting to `;hmr` and allows usage of HMR module by default in other code usage without needing to require it as globally required via gameloader
> chore: load HMR module by default

- lib/common/xmlparser.rb
- lib/games.rb
clear loot, npcs, pcs, room_desc GameObjs on new `<nav>` room movement. Prevents race condition of these not getting cleared upon entry to new room due to large xmlparsing.
Also removes no longer used `Map.last_seen_objects` from code as deprecated and removed from DR's `map_dr.rb` file.
> [all][xmlparser.rb] fix: Gameobj objs clearing on new nav room

- lib/attributes/skills.rb
Incorrectly used `Infomon.get("skill.%s.bonus" % ranks)` instead of how it's actually stored as `Infomon.get("skill.%s_bonus" % ranks)`
> [gs][skills.rb] bugfix: proper name of Skill bonus lookup

- lib/dragonrealms/commons/common-crafting.rb
Added 'You tuck' as successful response for putting away crafting items and logbooks on lines 249 and 433.
Would be nice to have them use the : *DRCI::PUT_AWAY_ITEM_SUCCESS_PATTERNS as in equipmanager.lic, but that'll be an update for another time...
> fix(dr): common-crafting.rb minor edit to add "You tuck"

- lib/dragonrealms/commons/common-moonmage.rb
refactor script to output multi-line array of results
Part 1 of 5 of a suite of astrology changes
- Part 1: #783 common-moonmage - update to peer_telescope for multi-line parsing of observation results
- Part 2: https://github.com/elanthia-online/dr-scripts/pull/7127 base - addition of settings support for astrology and walkingastro changes
- Part 3: https://github.com/elanthia-online/dr-scripts/pull/7125 astrology - refactor to account for peer_telescope change and addition of option to force vision predictions
- Part 4: https://github.com/elanthia-online/dr-scripts/pull/7124 walkingastro - extensive quality of life changes to default behaviour and new optional features
- Part 5: https://github.com/elanthia-online/dr-scripts/pull/7126 combat-trainer - refactor to account for …
> chore(dr): common-moonmage - refactor of peer_telescope

- lib/dragonrealms/commons/common-arcana.rb
backfired? provides a boolean status on whether the last spell cast using DRCA.cast? backfired.
- increase selectivity for auto_mana to pick out a backfire vs the (super-)set of all spell failures which shouldn't be penalised.
Updated spell failure patterns to include sorcery backlash, more specific regex for backfire, and missing target (dead before spell finished prepping)
> chore(dr): common-arcana - predicate to return backfire status and spell regex patterns update
