scripts/alias.lic, scripts/autostart.lic, scripts/go2.lic, scripts/jinx.lic, scripts/narost.lic, scripts/vars.lic, scripts/version.lic, scripts/xnarost.lic
Truing up scripts from Lich5 to Lich-5
=> Capturing all changes to scripts for 5.0.16

scripts/infomon.lic
Minor updates to regex for spells in infomon.
Barring logical errors or insights from the team requiring correction, this update will be merged into the main branch in 48 hours.
=> Updated spell regex in infomon

lich.rbw
This update modifies Spell cast routines to detect the Feat 'mental acuity' and to enable monk casting of minor mental spells with stamina instead of mana.  It is a moderate impact update, requires testing. 
Barring logical errors or commentary from members, this PR will be merged in 7 days (29 Aug) to allow ample testing time.
=> Update lich core to support monk stamina use

netlify.toml
Edit to see if I can bend jinx to my will for distro.
=> testing new netify for jinx

lich.rbw
Addresses Issue #11 
summary of changes
bumped version to 5.0.18
creaeted begin / rescue clause to gracefully fail out with 'false' in .active?
structured .active? to resolve request to keys in downcase when not Integer
structured .active? to resolve Symbol requests to keys in downcase
=> Effects to downcase for compare

scripts/lich5-update.lic
New method in file. 
Relies on json in data subdir
=> New Lich5 update method

scripts/lich5-update.lic
Created defect in Windows user downloads, needs immediate correction - this PR will be immediately merged and rolled back if there are errors noted.
=> BugFix: Windows users file permissions not retained

scripts/lich5-update.lic
Reverts elanthia-online/lich-5#15 - Fix not necessary so going back to align across repos
=> Revert "BugFix: Windows users file permissions not retained"

lich.rbw
Backing out 5.0.18 specific changes
=> Revert "Effects to downcase for compare"

lich.rbw
Reverts elanthia-online/lich-5#7
=> Revert "Update lich core to support monk stamina use"

scripts/lich5-update.lic
Add feature --revert to lich5-update
Bumped version to align with semver (1.3.1 was 1.2.2)
=> Add feature --revert to lich5-update

data/update-lich5.json
Includes 5.0.19 with three modifications due to PSM3
includes updated infomon (repairs regex for Cloak of Shadows and Raise Dead)
includes lich5-update new feature:  --revert
=> Updating for 5.0.19 announce / install

lib/constants.rb, lib/version.rb, lich.rbw
=> Breaking out version and constants

lib/gui-login.rb, lib/gui-saved-login.rb, lib/lich.rb, scripts/xnarost.lic
Address issue #45 and issue #46
=> GUI file changes darkmode / listview

lich.rbw
=> Global toggle variables #32

lib/init.rb, lib/lich.rb, lich.rbw
=> Direct frontend launch method (method 0)

lib/version.rb
=> Version bump 5.2 to 5.4

lib/version.rb
Reverts elanthia-online/lich-5#70
Agreeing to one major increment per release for new features.  Moving to 5.2 to account for two separate efforts.
=> Revert "Version bump 5.2 to 5.4"

data/update-lich5.json
=> Announcing 5.2.1 release

scripts/lich5-update.lic
Adds snapshot support irrespective of current Lich version to lich5-updater
=> Chore: Updating updater for snapshot support

scripts/go2.lic
=> [go2.lic] pull in combatant fix for go2

scripts/go2.lic, scripts/jinx.lic
Two scripts sync'd
;go2 (adds postoffice)
;jinx (adds pruning repositories)
=> Updating scripts for installer

lib/version.rb, lich.rbw
Update for future dev efforts
Version bumped to 5.3.1
NOTE:  this version has been rubocop auto-corrected for space / indentations.  Save your eyes and your sanity by ignoring whitepace changes.
=> Update Lich for Future Dev

lib/gui-manual-login.rb
updating GUI to support Lich Future Dev Feature
=> Update GUI Login to Support Lich Future Dev Feature

data/update-lich5.json
Announce 5.3.0 Lich to the world (of existing Lich5 users).
Do not merge until all other changes are merged - this takes the changes live for download.
=> JSON update for Wrayth release (5.3.0)

lib/util.rb
Craete opportunity for script writers to rely on a consistently performing function to find out how many silvers are presently carried.
More agnostic to regex than prior methods.
=> Adding global silver_count method

lich.rbw
=> Removing class TrueClass and class FalseClass

lib/version.rb
Updating for release.
corresponding JSON will not be updated as yet.  Terget for updating JSON and turning loose on the free world is 10 March 2022
=> Updating semver to 5.4.0 for release point

data/update-lich5.json
To true up during 5.3.0 from really early (5.0.16) release updates.
=> Upating json for 5.3.0 to do all files

data/update-lich5.json
=> Adding map.rb to 'refresh' so that preliminary testing can be executed

scripts/alias.lic, scripts/vars.lic
Rebase scripts with newer EO/scripts
=> Rebase with newer EO/scripts

data/update-lich5.json
This is it.  The big Kahuna.  The one you've all been wait. . . what?  Oh, all right.  Here.
=> 5.4.0 JSON (the red button)

scripts/go2.lic
=> Adding Lich::Util.silver_count to script to remove display error

lich.rbw
fix for detachable clients to get new uid and lichid.
=> UID/ID fix DetachableClient

lich.rbw
fix for FLAG inventory pushing spacing out of alignment on SF/Wrayth.
=> Lich Update - FLAG INVENTORY spacing issue

lich.rbw
Add ability to check version of a script as well as compare it to a version# for true/false.
Uses/Examples
```ruby
Script.version("infomon")
```
Returns: `1.18.12`
```ruby
Script.version("infomon", "1.18.11")
```
Returns: `false`
```ruby
if Script.version("infomon", "1.18.13")
echo "You need to update infomon in order to use this script"
echo "Please run ;jinx script update infomon --repo=elanthia-online"
exit
end
```
Returns false and gives echos to update script. example of how to check for dependent supplemental script versions.
=> Script Class Update - version check

data/update-lich5.json
JSON for 5.4.1 (24 hours later. . .)
=> Updating the Red Button with Updates

lib/init.rb
Creates a scripts/custom dir if one doesn't already exist.
=> Initial merge of DR changes to Lich5. 1/5 - init.rb adding creating of SCRIPT_DIR/custom if it doesn't exist

lib/map.rb
Adding DRisms to map.rb, primarily the room_objects tag and its uses.
=> Initial merge of DR changes to Lich5. 2/5 - map.rb adding room_objects tag

lib/xmlparser.rb
Adding :room_objects, :concentration, :max_concentration tags, and some small DRisms.
=> Initial merge of DR changes to Lich5. 3/5 - xmlparser.rb adding room_objects, :concentration, :max_concentration tags

lich.rbw
Depends on https://github.com/elanthia-online/lich-5/pull/130
Depends on https://github.com/elanthia-online/lich-5/pull/131
Depends on https://github.com/elanthia-online/lich-5/pull/132
Resolves https://github.com/elanthia-online/lich-5/issues/95
=> Initial merge of DR changes to Lich5. 4/5 - lich.rb DRisms

scripts/version.lic
Add option to get version of lib files.
=> Version support for library files

lib/gui-manual-login.rb
Corrects error reported by Athias - disconnect_button and sensitive= false; falseclass
=> Corrects error for disconnect_button.sensitive

lich.rbw
needs to read saved data from entry.dat, not from login_info
=> Fix custom launch from CLI

lib/xmlparser.rb, lich.rbw
Moving autostart and --start-scripts from class XMLParser
=> Moving autostart and --start-scripts out of xmlparser

lib/lich.rb, lib/messaging.rb, lich.rbw
Initial release
Supports Lich::Messaging.stream_window(msg, window) SENDS msg to stream window
Supports Lich::Messaging.monsterbold(msg)  RETURNS msg in monsterbold
=> Initial messaging.rb release

scripts/autostart.lic
Syncing with changes in eo/scripts for consistency.
=> Adding a check for DR / dependency runs

lich.rbw
Unclear how logins were being processed prior, but this brings DR saved entry information in line with GS saved entry information.
Also included, slight modification on dropping SU privileges - was causing issues.
=> Fix DR Logins from Saved Entry

lich.rbw
For testing and incorporation if approved.
=> Profanity init_str causes garbage in Genie

scripts/log.lic
DR uses configuration settings.  Something we need to do more broadly in GS.  This file works for both games.
=> Updating log.lic to support DR

lich.rbw
The best of both worlds now!  In stereo (no more room numbers for DR until DR has UID and we sort out the move issues)
=> Updating to remove room IDs from DR rooms

data/update-lich5.json
=> The Blue Button is ready.

lib/util.rb
Reverted all changes to util.rb due to a number of errors - this PR reintegrates the changes Ondrenian proposed to remove the Timeout interrupt as unreliable.  I'll work to reintegrate the other code that was committed as I can build / test it.
=> Adding Ondrenian silver_count fix after util.rb revert

lib/util.rb
v1.2.0 (2022-03-16)
* Add Lich::Util.quiet_command to mimic XML version
* Removed usage of Timeout::timeout
=> [lib] [util.rb] Add quiet_command and resolve Timeout issues

lich.rbw
=> [lich.rbw] Removing genie carriage returns

lib/map.rb, lich.rbw
As part of ongoing improvement, we need to be able to break out various lib/*.rb files by game (DR / GS).  This code begins that process but will be significantly enhanced / improved over time.  
As a point solution this works, but only addresses class Map and has no real path for correction.  Further enhancements required to stabilize and to extend.
=> [lich.rbw] Fix/Detect game and load appropriate map class

lib/lich.rb, lich.rbw
Reverts elanthia-online/lich-5#165
Temporarily backing this out due to GUI challenges.  Will roll back in with appropriate changes.
=> Revert "[lib] [lich.rb] Reducing db calls from Lich.display_lichid and Lich.display_roomid.  …"

lib/gui-login.rb, lib/gui-saved-login.rb
Correcting gui *.rb files to accept proposed boolean values in support of PR #201
=> Fix gui.rb files to support PR#201

lib/gui-login.rb, lib/gui-saved-login.rb
Reverts elanthia-online/lich-5#204
=> Revert "[lib][lich.rb] and supporting changes to gui *.rb files"

.gitattributes, lib/lich.rb, lich.rbw
Reverts elanthia-online/lich-5#206
Still trying to clean up.
=> Revert "Master -> Stage"

lib/gui-login.rb, lib/gui-saved-login.rb, lib/lich.rb, lich.rbw
This fix will help improve performance, and will remove issues some players are reporting with their GUI since our recent updates.  It will need to be advanced for 5.6.0 release to be captured in the installer.
=> Moving ROWO fix from staging to prod

lib/gui-login.rb, lib/gui-saved-login.rb, lib/lich.rb, lich.rbw
Reverts elanthia-online/lich-5#210
=> Revert "Moving ROWO fix from staging to prod"

lib/gui-login.rb, lib/gui-saved-login.rb, lib/lich.rb, lich.rbw
Reverts elanthia-online/lich-5#211
Reverting a reversion to restore!  I think.
=> Revert "Revert "Moving ROWO fix from staging to prod""

data/update-lich5.json, lib/version.rb
=> JSON announce and version bump 5.6.0

scripts/infomon.lic
Fix for PSM info now having type column and truncating certain skills
=> [infomon.lic] fix for PSM info output change

scripts/infomon.lic
Merging v1.18.14 changes to master
=> [infomon.lic] PSM fix

scripts/infomon.lic
Update to match version on EO/scripts
=> [infomon.lic] v1.18.15

lib/map_gs.rb
fixes a bug for matching current room for rooms without uids
=> [map_gs.rb] bug fix for current room

lich.rbw
Adds handling for nested double quotes in XML stream, and logging around bad XML tags, and fixes for better understanding of what's happening under the hood.
Also removes the anchor from the `settingsInfo` tag, since the DR tag at least, isn't always anchored.
With these changes I have no more hangs at start up, and rooms with nested double quote titles no longer spew forth XML errors.
I've found it very helpful seeing what lines triggered which subs too, and that's how I found the `settingsInfo` issue. 
```
2022-05-13 16:20:53: Invalid nested double quotes XML tags detected: <streamWindow id='room' title='Room' subtitle=" - [Avlea's Bows, "The Straight and Arrow"]" location='center' target='drop' ifClosed='' resident='true'/>
2022-05-13 16:20:53: Invalid nested double quotes XML tags …
```
=> [lich.rbw] Improved invalid XML handling

lib/update.rb
This fails just about every time I try - but let's try it again!
=> Syncing Staging to Master

lib/update.rb
As requested - interested to find out if this will work now on Win 11 with a space or spaces in the directory names as well as Linux platforms.
Fix #237
=> [update.rb] Updating to stdlib functions

lib/cman.rb, lib/feat.rb, lib/global_defs.rb, lib/shield.rb, lib/update.rb, lib/weapon.rb
This may be reverted nearly immediately if it causes errors.
=> Adding silently to 5.6.1

lich.rbw
Cleaning up a whole category of rooms with broken XML, and making our logging a bit more verbose so we capture newlines, and carriage returns, since that sucked to diagnose without those characters displaying...
=> [lich.rbw] More XML fixes for janky simu XML

lich.rbw
The stream says 
```xml
<right exist="13116574" noun="ball and chain">spiked ball and chain</right><clearStream id='inv' ifClosed=''/><pushStream id='inv'/>Your worn items are:
```
But it's a ball.
=> [lich.rbw] Add noun adjustment for Ball and Chain

lib/feat.rb
Fix stamina cost for dispel magic from 0 -> 30.
=> [feat.rb] stamina cost fix

lib/armor.rb
Initial addition of Armor.use functionality.
=> [armor.rb] Armor.use functionality

lib/spell.rb
fix for Mental Acuity to only work on MnM spells 1201-1220
=> [spell.rb] Mental Acuity & Armored Casting Fix

lib/util.rb
Add Lich::Util.command_xml and Lich::Util.command for non-quiet usage
=> [util.rb] v1.3.0 non-quiet versions of commands

.gitignore
- Adds DR Test, Fallen, Plat data directories to .gitignore
=> [.gitignore] Update for all DR instances

lib/gameobj.rb
fix elevated loading call and File.exists?
=> [gameobj.rb] Ruby 3.2 compatibility

lich.rbw
=> [lich.rbw] fix Spellsong class consolidation for Ruby 3.2

lib/init.rb
=> [meta][init.rb] Rubocop

lib/infomon/infomon.rb, spec/infomon_spec.rb
Additions by Tysong to add more things for infomon library
=> chore: additional infomon library stuff

lib/infomon/infomon.rb, lib/infomon/parser.rb, lib/infomon/status.rb, lich.rbw, spec/hmr_spec.rb, spec/infomon_spec.rb
Adds API for `Status.effect` and carries forward calmed? sleeping? etc.
=> chore: Adding infomon boolean status methods;

lib/infomon/activespell.rb, lib/xmlparser.rb, lich.rbw, spec/activespell_spec.rb
Adding back to infomon.  May be moved during `class Spell` rewrite, but presently here for backward compat.
=> chore: add activespell back to infomon module;

lib/infomon/cli.rb, lib/infomon/infomon.rb, lib/infomon/parser.rb, spec/infomon_spec.rb
Basic three function CLI.
Gussying up the output for `Infomon.show` is an exercise left to the reader.
=> chore: adding cli for infomon module

lib/util.rb
updates issue_command to allow `silent` value of `nil` to not modify silent value, and for `false` to make the command not silent on silent scripts.
=> [util.rb] update

.github/workflows/test.yml, Gemfile, Gemfile.lock, lib/status.rb, spec/status_spec.rb
=> chore: add status parser and rspec;

lib/spell.rb
Fix for Spell.cast method to repeat casting if generated spell preparation time due to a debuff in effect.
=> [spell.rb] - v1.2.4 multiple updates

lib/account.rb, lib/eaccess.rb
Add ability to `EAccess.account_name` and `EAccess.account_type` to return appropriate info
=> feat: add Account module (name, type, game, members)

lib/spell.rb
Updates to match EOL naming for `spell-list.xml` replacement to `effect-list.xml`
=> converting to effect-list.xml

R4LGTK3.iss
Add Lich & Ruby proper foldering to not conflict between version changes of Ruby and Lich5
=> chore: R4LGTK3.iss - update for subfolders

lib/infomon/parser.rb
=> [parser.rb] Society master rank fix

lib/attributes/char.rb, lib/attributes/skills.rb, lib/attributes/society.rb, lib/attributes/stats.rb
Reverts elanthia-online/lich-5#372
=> Revert "chore: infomon attribute libraries return explicit string/integer"

R4LGTK3.iss
Commenting out the Win compatibility line for 64-bit builds.
=> Update R4LGTK3.iss for 64bit Builds

lib/infomon/parser.rb
Use batch_set for additional integer parsing matches.
=> [parser.rb] batch_set additional parsing

lich.rbw
add line start anchor to regex pattern
=> [lich.rbw] anchor room uid/lichid display for resource xml

lib/infomon/activespell.rb
Add Council Task, Council Punishment, Briar Betrayer and all the various Aspect cooldowns
=> [activespell.rb] inactive_spells and ignore_spells update

lib/infomon/infomon.rb, lib/infomon/parser.rb, spec/infomon_spec.rb
Now uses blob_set for INFO, EXP, SKILL, and PSM
=> chore: Infomon - upsert_batch speed improvement

lib/infomon/parser.rb
redo of #380 since it got lost somewhere, and adds an anchor for SkillStart
=> [parser.rb] additional regex anchoring

lib/infomon/parser.rb
Update SkillStart to match for SKILL and SKILL BASE
=> [parser.rb] bugfix for SKILL BASE output start msg

lib/infomon/cli.rb, lib/infomon/parser.rb, lib/psms.rb, lib/psms/warcry.rb, spec/infomon_spec.rb, spec/psms_spec.rb
Add warcry.rb into PSMS module with proper hooks into various Infomon methods to work properly.
=> feat: GS4 warcry PSM module

lich.rbw
Reverts elanthia-online/lich-5#394
=> Revert "[lich.rbw] update $_SERVERSTRING_ cleanup, rubocop fixes"

lib/infomon/parser.rb
Ensure saving string or integer to DB depending on match.
=> [parser.rb] more explicit to_s and to_i

lib/attributes/char.rb, lib/game-loader.rb, lib/global_defs.rb, lich.rbw
Retry of #394, needs additional testing/fixing as currently breaks DragonRealms stuff.
Original description:
Moves DR & GS specific $SERVERSTRING corrections into methods from Game.open
Some rubocop fixes.
=> [lich.rbw] update $_SERVERSTRING_ cleanup, rubocop fixes 2

lib/infomon/parser.rb
bugfix for negative mana on StatEnd Regex
=> [parser.rb] bugfix StatEnd Mana negative

lib/infomon/infomon.rb, lib/infomon/parser.rb, lib/psms.rb, lib/psms/ascension.rb, spec/infomon_spec.rb
Creates an Ascension module as part of PSMS due to relying on similar architecture and system backend.
=> [ascension.rb] creation of Ascension module and infomon parsing

.gitignore, lib/update.rb
Adding beta test capabilities to `update.rb`.
=> [update.rb]Add beta test features

lib/global_defs.rb, lich.rbw
Addresses xml collisions reported from #410
=> [lich.rbw][global_defs.rb]Correct xml collisions for DR

lib/attributes/resource.rb, lib/game-loader.rb, lib/infomon/parser.rb, spec/infomon_spec.rb
Track GS4 profession service resource and suffusion. Relies on new `issue_command` from #425
=> feat: Resource module

lib/update.rb
Migrate staging changes into master to allow for updates to beta/rc releases for easier testing of existing users. Not bumping master version yet to not cause mass `;lich5-update --update` to trigger.
=> [update.rb] merge staging changes

lich.rbw
fix #304 for constants in ARGV after loading constants.rb
=> [lich.rbw] fix #304 for constants in ARGV after loading constants.rb

lib/infomon/cli.rb
Add `ASCENSION LIST ALL` and `RESOURCE` to `Infomon.sync` to get initial values set.
=> [cli.rb] update sync to pull ASCENSION and RESOURCE

lib/infomon/currency.rb, lib/infomon/parser.rb, spec/infomon_spec.rb
Add Lich::Currency module into the system using Infomon::Parser to populate data when seeing output from WEALTH, INFO, or TICKET BALANCE
=> feat: Currency module

lib/game-loader.rb
Need to actually load the new Currency module for it to work.
=> [game-loader.rb] require/load currency.rb

lib/bounty/task.rb, spec/bounty/task_spec.rb
Some tweaks to the API mostly related to heirloom tasks based on consumption with client scripts.
=> [Bounty API] Updates heirloom-related methods for easier use by scripts

lib/gameobj.rb
Return current XMLData.current_target_id as full npc/pc hash
=> feat: gameobj.rb add GameObj.target method

lib/infomon/infomon.rb, lib/infomon/xmlparser.rb, lich.rbw, spec/infomon_spec.rb
Allows for Infomon to parse XML game feed to set various variables/methods/data. Provides framework to also allow for `overwatch.lic` to utilize and become integrated into Lich-5. Fixes GameLoader possibly being loaded multiple times on startup as well.
=> feat: create Infomon::XMLParser

lib/bounty/parser.rb
Add Hinterwilds guard completion regex
```
You have located a pair of bronze bangle earrings and should bring it back to the tavernkeeper at Rawknuckle's Common House.
```
=> [parser.rb] update Bounty::Parser guard regex

lib/global_defs.rb
Remove reference to infomon and only show lnet help if running lnet
=> [global_defs.rb] ;help output cleanup

lib/infomon/cli.rb
Incorporating `dothistimeout` for shroud management.
=> [cli.rb] for Shroud of Deception

lib/experience.rb, lib/infomon/parser.rb, spec/infomon_spec.rb
=> [parser.rb] Infomon::Parser Death's Sting Update

lich.rbw
Just gating some detached-mode initialization entries to GS.
=> [lich.rbw] Gating some detached-mode init lines

lib/infomon/parser.rb, spec/infomon_spec.rb
Fix regex for WEALTH output update.
=> [parser.rb] wealth output regex update

lib/infomon/activespell.rb
Fix duration for Resist Nature 620 due to percentages in the name. Strip the percentage so that Lich can track properly
=> [activespell.rb] ResistNature/620 Fix

lib/script.rb
update messaging when pausing/unpausing scripts that are/are not paused
=> script.rb un|pause messaging

lib/global_defs.rb
Add `;help` output for Infomon.sync, and setting Lich/Real room IDs in room title.
=> [global_defs.rb] add various help output

lib/stash.rb
see conversation around:
https://discord.com/channels/226045346399256576/387286877327065108/1174787000348459159
=> [stash.rb] catch more shield removal messages

lib/infomon/infomon.rb, lib/infomon/parser.rb
bugfix for negative Experience before leveling up
=> [parser.rb] negative TNL exp value

lib/infomon/parser.rb
=> [parser.rb] Bard service update

lib/attributes/char.rb
Putting `Char.stance` back into play.  May need to consider if any of the stance percent options need to return.
=> [char.rb]-Adding Char.stance

R4LGTK3.iss, lib/version.rb
update for final 5.8.0 release
=> chore: Lich 5.8.0 staging release prep

lib/xmlparser.rb
=> [xmlparser.rb] rubocop cleanup

lib/character/group.rb, lib/constants.rb, lib/eaccess.rb, lib/game-loader.rb, lib/init.rb, lib/log.rb, lich.rbw
Port over Ondreian's Olib library Log module. Also did some code cleanup to load modules based on LIB_DIR instead of hardcoding that it should be relative to lich.rbw to support the fact that LIB_DIR could change at any time or via CLI launch parameters.
=> [all][log.rb] feat: Log module from Olib

lib/stash.rb
Use built in container method detection that looks inside container if it's contents.nil? to populate GameObj.containers and various content properly
=> [gs][stash.rb] use Stash.container(param) for sack detection

lib/global_defs.rb, lib/script.rb, lich.rbw
Moving out of lich.rbw
to global_defs.rb - some global script definitions
to global_defs.rb - aliases (with a recommended deprecation that can be built on)
to script.rb - some Script.method definitions
=> [chore] clean-up lich -> script and global def

lib/global_defs.rb
Changed comparison to assignment for proper resolution.
=> [all][global_defs.rb] bugfix: percentconcentration

R4LGTK3.iss, lib/version.rb
Break/fix release for Simu XML change
=> chore - prep 5.10.4 release

lib/dragonrealms/drinfomon/drdefs.rb
Clone of https://github.com/elanthia-online/dr-scripts/pull/7020
=> [dr][dr\drinfomon\drdefs.rb] Add fix for Shadow Servants

lib/dragonrealms/drinfomon/drdefs.rb
We now parse room_objects once and detect live and dead NPCs in one place, adding ordinals to all NPCs.
Works well for me, but should wait till the next release is out, so don't merge it yet, please.
=> [dr][drdefs.rb] Simplify npc detection and add ordinals to them

lib/util/update.rb
Change unnecessary `_respond` usage to `respond` to prevent XML processing of all lines when not needed
=> [all][update.rb] bugfix remove unnecessary _respond usage

lib/common/gui-login.rb
to accommodate new wider FE label
=> [all][gui-login.rb] fix: window width 550 to 590
